services:
  postgres:
    image: 'postgres:12-alpine'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'PGDATA: /var/lib/postgresql/data/pgdata/bank_service'
    ports:
      - '5431:5432'
    env_file:
      - .env